# Generated by Django 6.0.3 on 2026-04-05 17:02

from django.db import migrations, models


def rename_action_to_everyday(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Organization.objects.filter(category="action").update(category="everyday")


def rename_everyday_to_action(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    Organization.objects.filter(category="everyday").update(category="action")


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_add_career_category"),
    ]

    operations = [
        migrations.RunPython(
            rename_action_to_everyday,
            reverse_code=rename_everyday_to_action,
        ),
        migrations.AlterField(
            model_name="organization",
            name="category",
            field=models.CharField(
                choices=[
                    ("donate", "Donate"),
                    ("volunteer", "Volunteer"),
                    ("resource", "Resource"),
                    ("everyday", "Everyday"),
                    ("career", "Career"),
                ],
                max_length=20,
            ),
        ),
    ]
