# Generated by Django 6.0.3 on 2026-04-08 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0002_add_career_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="FocusArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="donate_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organization",
            name="evidence_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="geographic_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("local", "Local"),
                    ("state", "State"),
                    ("national", "National"),
                    ("multinational", "Multinational"),
                    ("global", "Global"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="legal_status",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="toolkit_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organization",
            name="volunteer_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organization",
            name="year_founded",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="EngagementOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engagement_type",
                    models.CharField(
                        choices=[
                            ("volunteer_in_person", "Volunteer In Person"),
                            ("volunteer_remote", "Volunteer Remote"),
                            ("donate_one_time", "Donate One Time"),
                            ("donate_recurring", "Donate Recurring"),
                            ("advocacy", "Advocacy"),
                            ("education", "Education"),
                            ("career", "Career"),
                            ("citizen_science", "Citizen Science"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "time_commitment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minutes", "Minutes"),
                            ("hours_per_week", "Hours Per Week"),
                            ("days_per_month", "Days Per Month"),
                            ("flexible", "Flexible"),
                            ("event_based", "Event Based"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True, default="")),
                ("skills_helpful", models.JSONField(blank=True, default=list)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_opportunities",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["engagement_type"],
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="focus_areas",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="organizations.focusarea"
            ),
        ),
        migrations.CreateModel(
            name="OperatingRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(max_length=2)),
                (
                    "region_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("name", models.CharField(max_length=200)),
            ],
            options={
                "ordering": ["country_code", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country_code", "region_code"),
                        name="unique_country_region",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="operating_regions",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizations",
                to="organizations.operatingregion",
            ),
        ),
    ]
