# Generated by Django 6.0.3 on 2026-04-25 23:28

import django.core.validators
import django.db.models.deletion
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models

CANONICAL_CATEGORIES = [
    ("donate", "Donate", "Learn more"),
    ("volunteer", "Volunteer", "Volunteer"),
    ("resource", "Resource", "Explore resources"),
    ("everyday", "Everyday", "Take action"),
    ("career", "Career", "Browse jobs"),
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("organizations", "Category")
    for slug, label, default_action_text in CANONICAL_CATEGORIES:
        Category.objects.update_or_create(
            slug=slug,
            defaults={
                "label": label,
                "default_action_text": default_action_text,
            },
        )


def unseed_categories(apps, schema_editor):
    Category = apps.get_model("organizations", "Category")
    Category.objects.filter(
        slug__in=[slug for slug, _, _ in CANONICAL_CATEGORIES],
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0001_initial"),
        ("organizations", "0002_add_career_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "slug",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=100)),
                (
                    "default_action_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Fallback CTA label used when an OrganizationCategory row has no per-(org, category) action_text. Empty string means the frontend decides.",
                        max_length=80,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["slug"],
            },
        ),
        migrations.RunPython(seed_categories, unseed_categories),
        migrations.CreateModel(
            name="SDG",
            fields=[
                (
                    "number",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(17),
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "SDG",
                "verbose_name_plural": "SDGs",
                "ordering": ["number"],
            },
        ),
        migrations.RemoveField(
            model_name="organization",
            name="category",
        ),
        migrations.RemoveField(
            model_name="organizationtranslation",
            name="action_text",
        ),
        migrations.AddField(
            model_name="organization",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="donate_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organization",
            name="evidence_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="geographic_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("local", "Local"),
                    ("state", "State"),
                    ("regional", "Regional"),
                    ("national", "National"),
                    ("multinational", "Multinational"),
                    ("global", "Global"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="legal_status",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="organization",
            name="toolkit_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organization",
            name="volunteer_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="organization",
            name="year_founded",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1800),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website_url",
            field=models.URLField(db_index=True),
        ),
        migrations.CreateModel(
            name="FocusArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("reviewed", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="focus_areas",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="organizations.focusarea"
            ),
        ),
        migrations.CreateModel(
            name="OperatingRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$", "Must be an ISO 3166-1 alpha-2 code."
                            )
                        ],
                    ),
                ),
                (
                    "region_code",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("name", models.CharField(max_length=200)),
                ("continent", models.CharField(blank=True, default="", max_length=20)),
            ],
            options={
                "ordering": ["country_code", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("country_code", "region_code"),
                        name="unique_country_region",
                    )
                ],
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="operating_regions",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizations",
                to="organizations.operatingregion",
            ),
        ),
        migrations.CreateModel(
            name="OrganizationCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="organization_entries",
                        to="organizations.category",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_entries",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "organization categories",
                "ordering": ["sort_order", "category__slug"],
                "unique_together": {("organization", "category")},
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name="organization",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="organizations",
                through="organizations.OrganizationCategory",
                to="organizations.category",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="sdgs",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="organizations.sdg"
            ),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("reviewed", models.BooleanField(default=False)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EngagementOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "engagement_type",
                    models.CharField(
                        choices=[
                            ("volunteer_in_person", "Volunteer In Person"),
                            ("volunteer_remote", "Volunteer Remote"),
                            ("donate_one_time", "Donate One Time"),
                            ("donate_recurring", "Donate Recurring"),
                            ("advocacy", "Advocacy"),
                            ("education", "Education"),
                            ("career", "Career"),
                            ("citizen_science", "Citizen Science"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "time_commitment",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("minutes", "Minutes"),
                            ("hours_per_week", "Hours Per Week"),
                            ("days_per_month", "Days Per Month"),
                            ("flexible", "Flexible"),
                            ("event_based", "Event Based"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                ("url", models.URLField(blank=True, default="")),
                ("location_bound", models.BooleanField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_opportunities",
                        to="organizations.organization",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="engagement_opportunities",
                        to="organizations.skill",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "engagement opportunities",
                "ordering": ["engagement_type"],
            },
        ),
        migrations.CreateModel(
            name="OrganizationCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                (
                    "action_text",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="organizations.organizationcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "organization category Translation",
                "db_table": "organizations_organizationcategory_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "unique_together": {("language_code", "master")},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="OrganizationEvaluation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evaluation_data",
                    models.JSONField(
                        help_text="Full evaluation payload matching curation/schema.json."
                    ),
                ),
                (
                    "ai_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Model ID that produced this evaluation.",
                        max_length=100,
                    ),
                ),
                (
                    "ai_recommendation",
                    models.CharField(
                        blank=True,
                        choices=[("include", "Include"), ("exclude", "Exclude")],
                        default="",
                        help_text="The AI's inclusion recommendation.",
                        max_length=20,
                    ),
                ),
                (
                    "ai_confidence",
                    models.IntegerField(
                        blank=True,
                        help_text="AI confidence in its recommendation (0–100).",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reviewer_reasoning",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Reasoning when overriding the AI recommendation.",
                    ),
                ),
                (
                    "reviewer_categories",
                    models.JSONField(
                        blank=True,
                        default=None,
                        help_text="Reviewer-chosen category slugs for the linked Organization. NULL means fall back to the AI's accessibility.categories list, filtered to known Category slugs. Edits here flow through to the linked Organization — on the APPROVED transition via the create path, and on subsequent admin saves via re-sync.",
                        null=True,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "nomination",
                    models.ForeignKey(
                        blank=True,
                        help_text="Source nomination that triggered this evaluation.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations",
                        to="nominations.nomination",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Linked organization (set on approval).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluations",
                        to="organizations.organization",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_evaluations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "created_at"], name="eval_status_created"
                    )
                ],
            },
        ),
    ]
