# Generated by Django 6.0.3 on 2026-04-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_add_enrichment_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagementopportunity",
            name="location_bound",
            field=models.BooleanField(default=False),
        ),
    ]
