# Generated by Django 6.0.4 on 2026-04-26 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_category_sdg_remove_organization_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationcategorytranslation",
            name="action_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
