# Generated by Django 6.0.3 on 2026-04-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_add_location_bound"),
    ]

    operations = [
        migrations.AddField(
            model_name="focusarea",
            name="reviewed",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="organization",
            name="geographic_scope",
            field=models.CharField(
                blank=True,
                choices=[
                    ("local", "Local"),
                    ("state", "State"),
                    ("regional", "Regional"),
                    ("national", "National"),
                    ("multinational", "Multinational"),
                    ("global", "Global"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
