# Generated by Django 6.0.3 on 2026-04-09 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_add_enrichment_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("reviewed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RemoveField(
            model_name="engagementopportunity",
            name="skills_helpful",
        ),
        migrations.AlterField(
            model_name="operatingregion",
            name="country_code",
            field=models.CharField(
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2}$", "Must be an ISO 3166-1 alpha-2 code."
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="evidence_score",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="year_founded",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1800),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="engagementopportunity",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="engagement_opportunities",
                to="organizations.skill",
            ),
        ),
    ]
