# Generated by Django 6.0.3 on 2026-04-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_add_skill_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationevaluation",
            name="ai_model",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Model ID that produced this evaluation.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="organizationevaluation",
            name="ai_recommendation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("include", "Include"),
                    ("exclude", "Exclude"),
                ],
                default="",
                help_text="The AI's inclusion recommendation.",
                max_length=20,
            ),
        ),
    ]
