# Generated by Django 6.0.3 on 2026-04-09 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0011_add_ai_model_and_recommendation"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationevaluation",
            name="ai_confidence",
            field=models.IntegerField(
                blank=True,
                help_text="AI confidence in its recommendation (0–100).",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
