# Generated by Django 6.0.3 on 2026-04-09 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_add_ai_confidence"),
    ]

    operations = [
        migrations.CreateModel(
            name="SDG",
            fields=[
                (
                    "number",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(17),
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "SDG",
                "verbose_name_plural": "SDGs",
                "ordering": ["number"],
            },
        ),
        migrations.AddField(
            model_name="organization",
            name="sdgs",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="organizations.sdg"
            ),
        ),
    ]
