# Generated by Django 6.0.3 on 2026-04-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_add_sdg_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationevaluation",
            name="ai_recommendation",
            field=models.CharField(
                blank=True,
                choices=[("include", "Include"), ("exclude", "Exclude")],
                default="",
                help_text="The AI's inclusion recommendation.",
                max_length=20,
            ),
        ),
    ]
