# Generated by Django 6.0.3 on 2026-04-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_add_sdg_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="operatingregion",
            name="continent",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
