# Generated by Django 6.0.3 on 2026-04-12 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0006_nomination_evaluation_attempts_and_more"),
        ("organizations", "0016_add_related_name_to_reviewed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationevaluation",
            name="nomination",
            field=models.ForeignKey(
                blank=True,
                help_text="Source nomination that triggered this evaluation.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="evaluations",
                to="nominations.nomination",
            ),
        ),
    ]
