# Generated by Django 6.0.3 on 2026-04-20 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0018_add_evaluation_indexes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationtranslation",
            name="action_text",
        ),
    ]
