# Generated by Django 6.0.3 on 2026-04-25 23:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=2048)),
                (
                    "categories",
                    models.JSONField(
                        help_text="List of category strings (e.g. volunteer, donate)."
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="SHA-256 hash of submitter IP for rate limiting.",
                        max_length=64,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("evaluating", "Evaluating"),
                            ("evaluated", "Evaluated"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "confirmation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("evaluation_attempts", models.PositiveSmallIntegerField(default=0)),
                (
                    "claimed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the worker last claimed this nomination for evaluation. Used to detect stuck EVALUATING claims.",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "claimed_at"],
                        name="nominations_status_4f9cc5_idx",
                    )
                ],
            },
        ),
    ]
