# Generated by Django 6.0.3 on 2026-04-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomination",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("evaluating", "Evaluating"),
                    ("evaluated", "Evaluated"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
