# Generated by Django 6.0.3 on 2026-04-06 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0002_alter_nomination_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomination",
            name="url",
            field=models.URLField(max_length=2048),
        ),
    ]
