# Generated by Django 6.0.3 on 2026-04-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0003_alter_nomination_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nomination",
            name="ip_hash",
            field=models.CharField(
                db_index=True,
                help_text="SHA-256 hash of submitter IP for rate limiting.",
                max_length=64,
            ),
        ),
    ]
