# Generated by Django 6.0.3 on 2026-04-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0006_nomination_evaluation_attempts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nomination",
            name="claimed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the worker last claimed this nomination for evaluation. Used to detect stuck EVALUATING claims.",
                null=True,
            ),
        ),
    ]
