# Generated by Django 6.0.3 on 2026-04-18 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nominations", "0007_add_claimed_at"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="nomination",
            index=models.Index(
                fields=["status", "claimed_at"], name="nominations_status_4f9cc5_idx"
            ),
        ),
    ]
